version: "3.7"
services:
    # image project
    mohjeranshop:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - laravel-mohjeranshop

    # php

    php:
        build:
        context: .
        dockerfile: Dockerfile
        container_name: php
        volumes:
        - ./:/var/www/html
        ports:
        - "8100:8100"
        networks:
        - laravel-mohjeranshop
    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 8180:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-mohjeranshop

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - 3388:3306
        networks: 
            - laravel-mohjeranshop
  
    #PHPMYADMIN  Service
    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin:latest
      environment:
        - PMA_HOST=mysql
        - PMA_USER=${DB_USERNAME}
        - PMA_PASSWORD=${DB_PASSWORD}
      restart: always
      ports:
        - 8181:80
      networks:
        - laravel-mohjeranshop

networks:
    laravel-mohjeranshop:
        driver: bridge