version: "3.7"

networks:
  database:
    external:
      name: database

services:
    # image project
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - mohjeranshop
            - mamp-shared
                
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 8180:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - mohjeranshop
            - mamp-shared

      #Node Service
    nodejs:
        image: node:lts-alpine
        restart: unless-stopped
        tty: true
        volumes:
        - ./:/var/www
        networks:
            - mohjeranshop

