#FROM php:7.4-fpm
FROM php:8.0-fpm

# Quando entrar no container, esse vai ser pasta principal que ele vai entrar
WORKDIR /var/www
# Aqui vai remover a pasta html
RUN rm -rf /var/www/html

# Para alterar o caminho da versão LTS do node acessar essa página
# https://github.com/nodesource/distributions#debmanual
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get update && apt-get install -y nodejs

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd sockets

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Setup our environment variables
ENV PHP_FILE_UPLOADS On
ENV PHP_ALLOW_URL_FOPEN On
ENV PHP_SHORT_OPEN_TAG On
ENV PHP_MEMORY_LIMIT 512M
ENV PHP_UPLOAD_MAX_FILESIZE 256M
ENV PHP_MAX_EXECUTION_TIME 5800

COPY --chown=www-data:www-data . /var/www
RUN chown -R www-data:www-data /var/www
RUN chmod -R 777 /var/www/storage/*

ADD ./docker/nginx/vhost.conf /etc/nginx/conf.d/default.conf

COPY . .

RUN npm install

# Liberar porta 9000 para iniciar o php-fpm server
EXPOSE 9000
